### ISSUE TITLE
Spaces or tabs..?

### ISSUE THREAD

**Issue by MarcDiethelm** [5an1ty/BitBot#10]
Do you prefer spaces or tabs for code indentation? Because the indentation style varies between files... I added a .editorconfig file locally that enforces two spaces, since that is what the majority of files use. Hey, but I'd much prefer to use tabs. ;)
I'll make a PR with the .editorconfig once I'm sure what you prefer.

**Comment by 5an1ty** [comment]
Two spaces sounds good indeed.

**Comment by 5an1ty** [comment]
Unrelated but a teaser on what I'm working on for the next generation of BitBot (heavily zoomed out):

<img width="1267" alt="screen shot 2015-11-15 at 18 50 53" src="https://cloud.githubusercontent.com/assets/5538404/11170070/30327f2c-8bca-11e5-971a-4552a40c43f6.png">

That's right, trading strategies with multiple combinations of different indicators where you can chose how many should agree in order to make a trade and a full admin web interface. I'd like to make it multiuser where you can create additional users with lower privilege (just to monitor).

The multi-user part might be too hard, not sure yet. Front end development get's me ...frustrated... sometimes is the least I can say, haha.

Keep in mind this is a spare time project and progress is slow, I just wanted to let everyone know I'm actually still working on BitBot which might not look like it if you look at my commit history :smile:.

**Comment by MarcDiethelm** [comment]
That looks very nice! Yep building web UIs is hard.

I've had several ideas about features for a frontend for BitBot too. ...I've been doing frontend for a somewhat longish time. Hit me up on [Twitter](https://twitter.com/booOfBorg) and maybe we can exchange some ideas?

**Comment by 5an1ty** [comment]
When I get a lot further, one of the things I was thinking about was to have a dashboard that gives you a brief overview of how the bot is performing. One of the components would be a candlestick chart with indications/markers on it where the bot bought /sold. I would prefer not to use any commercial products like Highcharts etc... But for now absolutely no clue how to work with canvas and draw charts, so I would love some help on things like that.

**Comment by MarcDiethelm** [comment]
This SVG-based library here looks pretty amazing and is on Github. http://techanjs.org/

**Comment by MarcDiethelm** [comment]
I was wondering, what's the status of next generation BitBot? Is there a possibility that I can preview or even hack on it? I've been using BitBot for quite a while now. Often times with quite some difficulties, which is why I keep making PRs for it when something about it really bugs me. But it sometimes also feels like a waste of resources patching BitBot, when its creator is already working on a new and improved version.

BitBot is becoming harder to maintain, e.g. for 2-3 months I was unable to run it because of problems with MongoJS/MongoDB. (This has happened before.) The workaround was to finally upgrade those dependencies and drop the candles db (thereby losing the ability to backtest with the data I collected over many months).

**Comment by 5an1ty** [comment]
Hi there! I'm going steady but progress is slow. Still haven't done much for the actual backend.
Can you tell me about the issues you have been having, because I never seem to have those. (never lost my candle db)

**Comment by MarcDiethelm** [comment]
I'll try to recreate the issues when I find more time.
In this case maybe my PRs do have some real value. Would you consider doing a release incorporating my patches?

**Comment by 5an1ty** [comment]
Yes the next version is still pretty far out. How many patches do you have?

**Comment by MarcDiethelm** [comment]
The ones you merged so far plus probably a tiny one that moves config file to a folder, so it can be exposed and persisted when running BitBot with [Dokku](https://github.com/dokku/dokku).
